// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjbwjelbmemzjnojclrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqYndqZWxibWVtempub2pjbHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzYzNTMsImV4cCI6MjA2NTUxMjM1M30.fN-I1liLkMtat3GdDJLTXKiEIm2vUjL6pM-BShwmgWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);